/*
 *    Copyright 2026 Hao Nguyen Tan
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package com.nestegg.portfolio.management.api.constants;

public final class TradingAgentConstants {
	public static final String ACTION_BUY = "BUY";
	public static final String ACTION_ACCUMULATE = "ACCUMULATE";
	public static final String ACTION_HOLD = "HOLD";
	public static final String ACTION_REDUCE = "REDUCE";
	public static final String ACTION_SELL = "SELL";

	public static final String ROLE_FUNDAMENTALS_ANALYST = "Fundamentals Analyst";
	public static final String ROLE_TECHNICAL_ANALYST = "Technical Analyst";
	public static final String ROLE_SENTIMENT_ANALYST = "Sentiment Analyst";
	public static final String ROLE_NEWS_MACRO_ANALYST = "News and Macro Analyst";
	public static final String ROLE_TRADER_AGENT = "Trader Agent";

	public static final String STANCE_STRONG_BULLISH = "Strong Bullish";
	public static final String STANCE_BULLISH = "Bullish";
	public static final String STANCE_NEUTRAL = "Neutral";
	public static final String STANCE_BEARISH = "Bearish";
	public static final String STANCE_STRONG_BEARISH = "Strong Bearish";

	public static final String RISK_VERY_HIGH = "Very High";
	public static final String RISK_HIGH = "High";
	public static final String RISK_MODERATE = "Moderate";
	public static final String RISK_LOW = "Low";

	public static final String DISCLAIMER = "Generated by deterministic NestEgg analysis agents for research and education only; this is not financial, investment, or trading advice.";
	public static final String SUMMARY_FUNDAMENTALS = "Evaluates valuation, profitability, growth, and income-statement quality.";
	public static final String SUMMARY_TECHNICALS = "Reviews short-, medium-, and long-horizon momentum with liquidity and beta overlays.";
	public static final String SUMMARY_SENTIMENT = "Uses the available rating and trading-status signal as a grounded proxy for market sentiment.";
	public static final String SUMMARY_NEWS = "Approximates macro and catalyst pressure from sector cyclicality and recent reported growth trends.";
	public static final String SUMMARY_TRADER = "Converts the analyst consensus and debate into a trade-intent score.";

	private TradingAgentConstants() {
	}
}
