/*
 *    Copyright 2025 Hao Nguyen Tan
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package com.nestegg.portfolio.management.api.agent;

import com.nestegg.portfolio.management.api.agent.dto.AgentReport;
import com.nestegg.portfolio.management.api.agent.dto.PortfolioDecision;
import com.nestegg.portfolio.management.api.agent.dto.ResearchDebate;
import com.nestegg.portfolio.management.api.agent.dto.RiskAssessment;
import com.nestegg.portfolio.management.api.agent.dto.TradingSuggestionResponse;
import com.nestegg.portfolio.management.api.entities.StockFinancialRatio;
import com.nestegg.portfolio.management.api.entities.StockIncomeStatement;
import com.nestegg.portfolio.management.api.entities.StockOverview;
import com.nestegg.portfolio.management.api.entities.StockRatio;
import com.nestegg.portfolio.management.api.exceptions.ResourceNotFoundException;
import com.nestegg.portfolio.management.api.repositories.StockFinancialRatioRepository;
import com.nestegg.portfolio.management.api.repositories.StockIncomeStatementRepository;
import com.nestegg.portfolio.management.api.repositories.StockOverviewRepository;
import com.nestegg.portfolio.management.api.repositories.StockRatioRepository;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Optional;
import java.util.function.Function;

@Service
public class TradingAgentServiceImpl implements TradingAgentService {
	private static final String DISCLAIMER = "Generated by deterministic NestEgg analysis agents for research and education only; this is not financial, investment, or trading advice.";

	private final StockOverviewRepository stockOverviewRepository;
	private final StockRatioRepository stockRatioRepository;
	private final StockFinancialRatioRepository stockFinancialRatioRepository;
	private final StockIncomeStatementRepository stockIncomeStatementRepository;

	public TradingAgentServiceImpl(
			StockOverviewRepository stockOverviewRepository,
			StockRatioRepository stockRatioRepository,
			StockFinancialRatioRepository stockFinancialRatioRepository,
			StockIncomeStatementRepository stockIncomeStatementRepository
	) {
		this.stockOverviewRepository = stockOverviewRepository;
		this.stockRatioRepository = stockRatioRepository;
		this.stockFinancialRatioRepository = stockFinancialRatioRepository;
		this.stockIncomeStatementRepository = stockIncomeStatementRepository;
	}

	@Override
	public TradingSuggestionResponse suggest(String ticker) {
		String normalizedTicker = normalizeTicker(ticker);
		if (!StringUtils.hasText(normalizedTicker)) {
			throw new IllegalArgumentException("Ticker is required");
		}

		StockOverview overview = stockOverviewRepository.findBySymbol(normalizedTicker)
				.orElseThrow(() -> new ResourceNotFoundException("Stock overview not found for ticker: " + normalizedTicker));
		StockRatio ratio = stockRatioRepository.findByTicker(normalizedTicker).orElse(null);
		StockFinancialRatio financialRatio = stockFinancialRatioRepository.findTopByTickerOrderByYearDescQuarterDesc(normalizedTicker).orElse(null);
		StockIncomeStatement incomeStatement = stockIncomeStatementRepository.findTopByTickerOrderByYearDescQuarterDesc(normalizedTicker).orElse(null);
		List<StockIncomeStatement> incomeHistory = stockIncomeStatementRepository.findTop8ByTickerOrderByYearDescQuarterDesc(normalizedTicker);

		AgentReport fundamentals = fundamentalsAnalyst(overview, ratio, financialRatio, incomeStatement);
		AgentReport technicals = technicalAnalyst(overview, ratio);
		AgentReport sentiment = sentimentAnalyst(overview);
		AgentReport news = newsAnalyst(overview, incomeHistory);
		List<AgentReport> analystReports = List.of(fundamentals, sentiment, news, technicals);

		ResearchDebate debate = researchDebate(analystReports, overview, ratio);
		int analystConsensus = weightedAverage(List.of(fundamentals.score(), sentiment.score(), news.score(), technicals.score()), List.of(40, 15, 15, 30));
		AgentReport trader = traderAgent(analystConsensus, overview, ratio, debate);
		RiskAssessment riskAssessment = riskManagers(overview, ratio, financialRatio, trader.score());
		PortfolioDecision decision = portfolioManager(trader.score(), riskAssessment, overview);

		return new TradingSuggestionResponse(
				normalizedTicker,
				firstNonBlank(overview.getName(), normalizedTicker),
				LocalDate.now(),
				decision.action(),
				clamp(trader.score() - Math.max(0, riskAssessment.riskScore() - 55) / 3),
				decision.targetWeightPercent(),
				debate.synthesis(),
				riskAssessment.constraints(),
				analystReports,
				debate,
				trader,
				riskAssessment,
				decision,
				DISCLAIMER
		);
	}

	private AgentReport fundamentalsAnalyst(StockOverview overview, StockRatio ratio, StockFinancialRatio financialRatio, StockIncomeStatement incomeStatement) {
		double pe = firstNonNull(valueOf(financialRatio, StockFinancialRatio::getPriceToEarning), valueOf(ratio, StockRatio::getPriceToEarning), 0D);
		double pb = firstNonNull(valueOf(financialRatio, StockFinancialRatio::getPriceToBook), valueOf(ratio, StockRatio::getPriceToBook), 0D);
		double roe = firstNonNull(valueOf(financialRatio, StockFinancialRatio::getRoe), valueOf(ratio, StockRatio::getRoe), 0D);
		double revenueGrowth = firstNonNull(valueOf(incomeStatement, StockIncomeStatement::getYearRevenueGrowth), 0D);
		double margin = firstNonNull(valueOf(financialRatio, StockFinancialRatio::getPostTaxMargin), valueOf(ratio, StockRatio::getProfitMargin), 0D);

		int score = clamp(45
				+ scoreIf(pe > 0D && pe <= 12D, 14, pe > 25D, -12)
				+ scoreIf(pb > 0D && pb <= 1.8D, 10, pb > 4D, -8)
				+ boundedContribution(roe, 0.5D, -10, 18)
				+ boundedContribution(revenueGrowth, 0.35D, -12, 14)
				+ boundedContribution(margin, 0.25D, -8, 10));

		return new AgentReport(
				"Fundamentals Analyst",
				stanceFor(score),
				score,
				"Evaluates valuation, profitability, growth, and income-statement quality.",
				List.of(
						metric("P/E", pe),
						metric("P/B", pb),
						metric("ROE", roe),
						metric("Revenue growth", revenueGrowth),
						metric("Post-tax margin", margin)
				)
		);
	}

	private AgentReport technicalAnalyst(StockOverview overview, StockRatio ratio) {
		double week = firstNonNull(overview.getDeltaInWeek(), 0D);
		double month = firstNonNull(overview.getDeltaInMonth(), 0D);
		double year = firstNonNull(overview.getDeltaInYear(), 0D);
		double beta = firstNonNull(valueOf(ratio, StockRatio::getBetaIndex), 1D);
		long volume = firstNonNull(valueOf(ratio, StockRatio::getTradeVolume), 0L);

		int score = clamp(50
				+ boundedContribution(week, 1D, -15, 15)
				+ boundedContribution(month, 0.55D, -12, 12)
				+ boundedContribution(year, 0.15D, -10, 10)
				+ (volume >= 1_000_000L ? 5 : 0)
				+ (beta > 1.5D ? -6 : beta < 0.7D ? 3 : 0));

		return new AgentReport(
				"Technical Analyst",
				stanceFor(score),
				score,
				"Reviews short-, medium-, and long-horizon momentum with liquidity and beta overlays.",
				List.of(
						metric("Weekly change %", week),
						metric("Monthly change %", month),
						metric("Yearly change %", year),
						"Trade volume: " + volume,
						metric("Beta", beta)
				)
		);
	}

	private AgentReport sentimentAnalyst(StockOverview overview) {
		double rating = firstNonNull(overview.getRating(), 0D);
		boolean activelyTraded = Boolean.TRUE.equals(overview.getIsActivelyTraded());
		int score = clamp(45 + boundedContribution(rating - 5D, 8D, -20, 25) + (activelyTraded ? 6 : -8));

		return new AgentReport(
				"Sentiment Analyst",
				stanceFor(score),
				score,
				"Uses the available rating and trading-status signal as a grounded proxy for market sentiment.",
				List.of(
						metric("Stock rating", rating),
						"Actively traded: " + activelyTraded,
						"Exchange: " + firstNonBlank(overview.getExchange(), "unknown")
				)
		);
	}

	private AgentReport newsAnalyst(StockOverview overview, List<StockIncomeStatement> incomeHistory) {
		double averageGrowth = incomeHistory.stream()
				.map(StockIncomeStatement::getYearRevenueGrowth)
				.filter(value -> value != null)
				.mapToDouble(Double::doubleValue)
				.average()
				.orElse(0D);
		String industry = firstNonBlank(overview.getIndustry(), "Unclassified");
		int sectorAdjustment = sectorAdjustment(industry);
		int score = clamp(50 + boundedContribution(averageGrowth, 0.3D, -12, 12) + sectorAdjustment);

		return new AgentReport(
				"News and Macro Analyst",
				stanceFor(score),
				score,
				"Approximates macro and catalyst pressure from sector cyclicality and recent reported growth trends.",
				List.of(
						"Industry: " + industry,
						metric("Average reported revenue growth", averageGrowth),
						"Sector macro adjustment: " + sectorAdjustment
				)
		);
	}

	private ResearchDebate researchDebate(List<AgentReport> reports, StockOverview overview, StockRatio ratio) {
		AgentReport best = reports.stream().max(java.util.Comparator.comparing(AgentReport::score)).orElse(reports.getFirst());
		AgentReport worst = reports.stream().min(java.util.Comparator.comparing(AgentReport::score)).orElse(reports.getFirst());
		double liquidity = firstNonNull(valueOf(ratio, StockRatio::getTradeVolume), 0L) / 1_000_000D;
		String bullish = "Bull case: " + best.role() + " is " + best.stance().toLowerCase(Locale.ROOT) + " because " + best.evidence().getFirst() + ".";
		String bearish = "Bear case: " + worst.role() + " flags " + worst.stance().toLowerCase(Locale.ROOT) + " conditions; liquidity is " + round(liquidity) + " million shares and adverse revisions can amplify drawdowns.";
		String synthesis = String.format(Locale.US,
				"%s shows a blended opportunity where analyst support must be balanced against valuation, momentum, liquidity, and sector risk before sizing the trade.",
				firstNonBlank(overview.getName(), overview.getSymbol()));
		return new ResearchDebate(bullish, bearish, synthesis);
	}

	private AgentReport traderAgent(int consensus, StockOverview overview, StockRatio ratio, ResearchDebate debate) {
		double monthlyMomentum = firstNonNull(overview.getDeltaInMonth(), 0D);
		double pe = firstNonNull(valueOf(ratio, StockRatio::getPriceToEarning), 0D);
		int score = clamp(consensus + (monthlyMomentum > 8D ? 4 : monthlyMomentum < -8D ? -4 : 0) + (pe > 0D && pe < 10D ? 3 : 0));
		return new AgentReport(
				"Trader Agent",
				stanceFor(score),
				score,
				"Converts the analyst consensus and debate into a trade-intent score.",
				List.of(
						"Weighted analyst consensus: " + consensus,
						metric("Monthly momentum adjustment", monthlyMomentum),
						debate.synthesis()
				)
		);
	}

	private RiskAssessment riskManagers(StockOverview overview, StockRatio ratio, StockFinancialRatio financialRatio, int traderScore) {
		double beta = firstNonNull(valueOf(ratio, StockRatio::getBetaIndex), 1D);
		double debtOnEquity = firstNonNull(valueOf(financialRatio, StockFinancialRatio::getDebtOnEquity), valueOf(ratio, StockRatio::getPayableOnEquity), 0D);
		double weeklyMove = Math.abs(firstNonNull(overview.getDeltaInWeek(), 0D));
		long volume = firstNonNull(valueOf(ratio, StockRatio::getTradeVolume), 0L);

		int riskScore = clamp(35
				+ boundedContribution(beta - 1D, 18D, -8, 22)
				+ boundedContribution(debtOnEquity, 0.12D, 0, 18)
				+ boundedContribution(weeklyMove, 1.1D, 0, 18)
				+ (volume > 0L && volume < 300_000L ? 12 : 0)
				+ (traderScore < 40 ? 6 : 0));

		List<String> constraints = new ArrayList<>();
		constraints.add(metric("Beta", beta));
		constraints.add(metric("Debt on equity", debtOnEquity));
		constraints.add(metric("Absolute weekly move %", weeklyMove));
		if (volume > 0L && volume < 300_000L) {
			constraints.add("Liquidity below preferred threshold: " + volume + " shares");
		}
		if (traderScore < 45) {
			constraints.add("Trader score is below accumulation threshold");
		}

		return new RiskAssessment(riskLevel(riskScore), riskScore, round(Math.max(5D, Math.min(18D, 8D + riskScore / 10D))), constraints);
	}

	private PortfolioDecision portfolioManager(int traderScore, RiskAssessment riskAssessment, StockOverview overview) {
		int adjustedScore = clamp(traderScore - Math.max(0, riskAssessment.riskScore() - 55) / 2);
		String action = actionFor(adjustedScore);
		boolean approved = !"SELL".equals(action) && !("REDUCE".equals(action) && riskAssessment.riskScore() >= 70);
		double targetWeight = switch (action) {
			case "BUY" -> 8D;
			case "ACCUMULATE" -> 5D;
			case "HOLD" -> 0D;
			case "REDUCE" -> -4D;
			default -> -8D;
		};
		if ("High".equals(riskAssessment.riskLevel()) || "Very High".equals(riskAssessment.riskLevel())) {
			targetWeight = targetWeight > 0D ? targetWeight / 2D : targetWeight;
		}
		String rationale = String.format(Locale.US,
				"Portfolio manager %s the %s action after adjusting score to %d for %s risk.",
				approved ? "approves" : "does not approve",
				action.toLowerCase(Locale.ROOT),
				adjustedScore,
				riskAssessment.riskLevel().toLowerCase(Locale.ROOT));
		return new PortfolioDecision(action, approved, round(targetWeight), rationale + " Ticker: " + firstNonBlank(overview.getSymbol(), "unknown") + ".");
	}

	private String actionFor(int score) {
		if (score >= 75) return "BUY";
		if (score >= 60) return "ACCUMULATE";
		if (score >= 45) return "HOLD";
		if (score >= 30) return "REDUCE";
		return "SELL";
	}

	private String riskLevel(int riskScore) {
		if (riskScore >= 80) return "Very High";
		if (riskScore >= 65) return "High";
		if (riskScore >= 45) return "Moderate";
		return "Low";
	}

	private String stanceFor(int score) {
		if (score >= 75) return "Strong Bullish";
		if (score >= 60) return "Bullish";
		if (score >= 45) return "Neutral";
		if (score >= 30) return "Bearish";
		return "Strong Bearish";
	}

	private int sectorAdjustment(String industry) {
		String normalized = industry.toLowerCase(Locale.ROOT);
		if (normalized.contains("technology") || normalized.contains("software")) return 5;
		if (normalized.contains("bank") || normalized.contains("financial")) return 2;
		if (normalized.contains("utility") || normalized.contains("consumer")) return 1;
		if (normalized.contains("real estate") || normalized.contains("material")) return -2;
		if (normalized.contains("energy") || normalized.contains("oil")) return -3;
		return 0;
	}

	private int weightedAverage(List<Integer> scores, List<Integer> weights) {
		int weightedScore = 0;
		int totalWeight = 0;
		for (int i = 0; i < scores.size(); i++) {
			weightedScore += scores.get(i) * weights.get(i);
			totalWeight += weights.get(i);
		}
		return Math.round((float) weightedScore / totalWeight);
	}

	private String metric(String label, Double value) {
		return label + ": " + round(value);
	}

	private int scoreIf(boolean positiveCondition, int positive, boolean negativeCondition, int negative) {
		if (positiveCondition) return positive;
		return negativeCondition ? negative : 0;
	}

	private int boundedContribution(double value, double multiplier, int floor, int ceiling) {
		return (int) Math.round(Math.max(floor, Math.min(ceiling, value * multiplier)));
	}

	private int clamp(int score) {
		return Math.max(0, Math.min(100, score));
	}

	private Double round(Double value) {
		return value == null ? 0D : Math.round(value * 100D) / 100D;
	}

	@SafeVarargs
	private final <T> T firstNonNull(T... values) {
		for (T value : values) {
			if (value != null) return value;
		}
		return null;
	}

	private String firstNonBlank(String... values) {
		for (String value : values) {
			if (StringUtils.hasText(value)) return value;
		}
		return "";
	}

	private String normalizeTicker(String ticker) {
		return ticker == null ? "" : ticker.trim().toUpperCase(Locale.ROOT);
	}

	private <T, R> R valueOf(T source, Function<T, R> mapper) {
		return Optional.ofNullable(source).map(mapper).orElse(null);
	}
}
