spring:
  application:
    name: gateway

management:
  endpoints:
    web:
      exposure:
        include: "health"
  tracing:
    sampling:
      probability: 1.0 # 1.0 means 100% of requests are traced. Lower this in production!
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: "http://localhost:4318/v1/traces"

server:
  port: 1080
  servlet:
    context-path: /nestegg/api
